const nota1 = 4.5;
const nota2 = 3.8;
const nota3 = 2.9;
const nota4 = 4.0;
let suma = nota1 + nota2 + nota3 + nota4;
let promedio = suma / 4;
let resultado = (nota1 + nota2) * (nota3 + nota4) / 2;
console.log("Suma de las notas: " + suma);
console.log("Promedio: " + promedio);
console.log("Resultado de la operación: " + resultado);