const PRODUCCION_POR_HORA = 250;
const HORAS_TRABAJADAS = 8;
const CAPACIDAD_CAJA = 12;
let totalPiezas;
let cajasLlenas;
let piezasSueltas;
totalPiezas = PRODUCCION_POR_HORA * HORAS_TRABAJADAS;
cajasLlenas = Math.floor(totalPiezas / CAPACIDAD_CAJA);
piezasSueltas = totalPiezas % CAPACIDAD_CAJA;
console.log("Total de piezas producidas: " + totalPiezas);
console.log("Cajas llenas: " + cajasLlenas);
console.log("Piezas sueltas: " + piezasSueltas);